Enhancment/variable color palette
Cocktail-Wizard/Cocktail_Wizard pull request #114
Opened 2024-04-12 17:39 UTC by AdelnorAcmorux

# Description de la Pull Request

## Description brève des modifications

Expliquez brièvement le but général des modifications apportées par cette pull request.

## Détail des modifications

Veuillez expliquer en détail les changements effectués par cette pull request.
Présentez de manière concise ce que fait chaque modification.

## Objectif des modifications/Problème résolu (le cas échéant)

Décrivez précisément l'objectif de cette pull request.
Expliquez pourquoi ces modifications sont nécessaires et comment elles améliorent ou résolvent des problèmes spécifiques.
Utilisez des balises comme "Fixes #numéro-du-ticket" ou "Résout le problème de [description]" si applicable.

## Captures d'écran (le cas échéant)

Si pertinent, incluez des captures d'écran ou des gifs animés pour illustrer visuellement les modifications apportées.

## Étapes de vérification

Fournissez des étapes détaillées que le relecteur peut suivre pour vérifier vos modifications :

1. Étape 1...
2. Étape 2...
3. etc.

## Notes pour le relecteur

Incluez ici des informations supplémentaires pertinentes ou des points spécifiques sur lesquels le relecteur devrait se concentrer lors de l'examen de cette demande de pull request.

2024-04-12 17:42 UTC, Vianpyro requested changes

2024-04-12 17:42 UTC, Vianpyro commented on ressources/modeles/modale_publication.php
> +                    <textarea id="description-texte" name="description-cocktail" rows="4" cols="50" placeholder="Une description n'est pas nécessaire, mais elle permet à notre communauté de voir à tr
Pas de `<br>` >:(

2024-04-12 17:42 UTC, Vianpyro commented on ressources/styles/Elianto/__MACOSX/Elianto/._Elianto-Regular.otf
wtf is this folder?!

2024-04-12 17:42 UTC, Vianpyro commented on ressources/styles/Elianto/__MACOSX/Elianto/._Elianto-Regular.ttf
wtf is this folder?!

2024-04-12 21:52 UTC, Amelo32 requested changes, later dismissed
modal fonctionne po

2024-04-22 17:09 UTC, AdelnorAcmorux commented
OKAY MESSIEURS,

J'ai besoin que vous alliez vérifier si les thèmes de couleur vous plaisent. N'hésitez pas à apporter tout commentaire que vous souhaiteriez. Je connais bien mes variables, donc je devrais pouvoir apporter des changements assez rapidement. Je travaille ce soir et je dois partir autour de 15h, donc je veux avancer le plus vite possible.

Pour changer de mode de couleur, il vous suffit de changer le thème de votre navigateur, puis de vérifier les deux modes et de tester chaque page et élément. J'aimerais savoir si j'ai manqué quelque chose dans les interactions ou autre chose. Si vous voulez apporter une modification à une couleur, n'hésitez pas. Si vous avez des questions, allez-y !

2024-04-22 20:19 UTC, Vianpyro requested changes

2024-04-22 20:19 UTC, Vianpyro commented on pages/galerie.php
Saurais-tu m'expliquer ton intention avec cette modification?

2024-04-22 20:19 UTC, Vianpyro commented on ressources/styles/connexion.css
> +}
Si l'on souhaite généraliser l'utilisation d'une balise, il serait préférable de l'intégrer dans le fichier `main.js`. 
Autrement, on risque de compromettre l'uniformité du site.

2024-04-22 20:19 UTC, Vianpyro commented on ressources/styles/index.css
> +    color: var(--palette-lighttext-color);
Pareil, à gérer depuis `main.js`

2024-04-23 14:00 UTC, AdelnorAcmorux commented on pages/galerie.php
Idk what u mean, ton comments est vide

2024-04-23 15:58 UTC, Vianpyro commented
Je suis réticent à l'idée d'utiliser une police d'écriture trop obscure qui nécessiterait son intégration dans l'application web et son téléchargement par l'utilisateur.

2024-04-23 19:09 UTC, Vianpyro requested changes
![penis](https://imgs.search.brave.com/V_yiBQ4mmC5r-sRUr5dTU3J7YpCjL3AkKfei1d7Zt9o/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YTMuZ2lwaHkuY29t/L21lZGlhLzI2Z0Jq/cGx4UlU1RVVodmxT/LzIwMC5naWY_Y2lk/PTc5MGI3NjExYjhk/MXRnbmFrczRlcDBy/N3gzY21kY2ZkcXF0/anBjam9zdHo1dXpz/MyZlcD12MV9naWZz/X3NlYXJjaCZyaWQ9/MjAwLmdpZiZjdD1n.gif)

2024-04-23 19:10 UTC, Vianpyro approved these changes, later dismissed

2024-04-24 01:11 UTC, Vianpyro approved these changes

2024-04-24 01:11 UTC, Amelo32 approved these changes

2024-04-24 01:11 UTC, merged