Ajout de la fenêtre de publication d'un cocktail
Cocktail-Wizard/Cocktail_Wizard pull request #67
Opened 2024-03-26 13:40 UTC by AdelnorAcmorux

# Description de la Pull Request

Création de la feature "publication"

Expliquez brièvement le but général des modifications apportées par cette pull request.

Creation de la modal, l'utilisateur peux écrire un no,, une description, un texte de préparation, ajouté des ingredients et ajouter une image.

L'ajout d'ingredient est basé sur les ingredients que nous avons. Quantité doit etre numerique. Unite de mesure predeterminer.

Preview d'une image rajouter pa l'utilisateur

## Captures d'écran (le cas échéant)
![image](https://github.com/Vianpyro/Cocktail_Wizard/assets/140647944/adf61c76-c84e-4fed-91f4-bf20fa17d6b8)

2024-03-26 14:15 UTC, Vianpyro requested changes

2024-03-26 15:53 UTC, Amelo32 submitted a review, later dismissed

2024-04-01 16:31 UTC, Vianpyro submitted a review, later dismissed
Belle avancée dans l'ensemble, n'hésite pas à aller voir le code dans [`index.js`](https://github.com/Vianpyro/Cocktail_Wizard/blob/develop/ressources/scripts/index.js) pour l'ouverture de la modale, ca pourrait t'aider (en tous cas je l'espère)

2024-04-05 03:04 UTC, Vianpyro requested changes, later dismissed
Excellent travail, @AdelnorAcmorux! Je tiens à souligner les gros efforts que tu as investis dans cette PR.
Cependant, j'ai repéré quelques petites erreurs/minor issues qui nécessitent notre attention avant de fusionner cette PR. Rien de majeur, mais corriger ces points renforcerait la qualité globale du code.
J'ai remarqué beaucoup de balises `<br />`, il faudra penser à les retirer.

2024-04-05 03:04 UTC, Vianpyro commented on pages/galerie.php
> +            <img id="btnPublish" src="../ressources/images/feather.svg" alt="Feather" width="24" height="24">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
Les attributs CSS devraient être dans un fichier CSS.
```suggestion
            <img id="btnPublish" src="../ressources/images/feather.svg" alt="Publier">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/galerie_connecte.php
> +    <link rel="stylesheet" href="../ressources/styles/publication.css">
Les autres fonctionnent sans le `../`, c'est du détail mais c'est plus simpa que tout soit unis x')
```suggestion
    <link rel="stylesheet" href="ressources/styles/publication.css">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/galerie_connecte.php
> +            <img id="btnPublish" src="../ressources/images/feather.svg" alt="Feather" width="24" height="24">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
Les attributs CSS devraient être dans un fichier CSS.
```suggestion
            <img id="btnAbout" src="../ressources/images/info.svg" alt="Infos">
        </button>
        <button type="button" id="publish" data-bs-toggle="modal" data-bs-target="#monModal">
            <img id="btnPublish" src="../ressources/images/feather.svg" alt="Publier">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/galerie_connecte.php
> +                                    <img class="btn-icon" src="../ressources/images/plus.svg" alt="+">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
```suggestion
                                    <img class="btn-icon" src="../ressources/images/plus.svg" alt="Ajouter un ingrédient">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/monbar.php
>              <img id="btnPublish" src="../ressources/images/feather.svg" alt="Feather" width="24" height="24">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
Les attributs CSS devraient être dans un fichier CSS.
```suggestion
            <img id="btnPublish" src="../ressources/images/feather.svg" alt="Publier">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/monbar.php
> +                                    <img class="btn-icon" src="../ressources/images/plus.svg" alt="+">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
```suggestion
                                    <img class="btn-icon" src="../ressources/images/plus.svg" alt="Ajouter un ingrédient">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/testdropdown.html
> +    </style>
Je suppose que tu sépareras dans un fichier CSS?

2024-04-05 03:04 UTC, Vianpyro commented on pages/testdropdown.html
> +            <input type="text" placeholder="Ajouter un ingredient..." id="boite-recherche" onkeyup="filterFunction()">
Pas de JavaScript dans les balises HTML, ajoute un `eventListener` dans un fichier séparé
```suggestion
            <input type="text" placeholder="Ajouter un ingredient..." id="boite-recherche">
```

2024-04-05 03:04 UTC, Vianpyro commented on pages/testdropdown.html
> +        const allIngredients = ["Vodka", "Rhum", "Gin", "Tequila", "Whiskey", "Triple sec", "Sirop simple", "Jus de citron", "Jus de lime", "Jus d'orange", "Jus de canneberge", "Grenadine", "Jus de p
N'oublie pas d'utiliser l'API plutot qu'une liste magique

2024-04-05 03:04 UTC, Vianpyro commented on pages/testdropdown.html
> +    </script>
Je suppose que tu sépareras dans un fichier JavaScript?

2024-04-05 03:04 UTC, Vianpyro commented on ressources/modeles/modale_publication.html
> +                                <img class="btn-icon" src="../ressources/images/plus.svg" alt="+">
L'attribut `alt` doit décrire l'objectif ou la fonction du bouton plutôt que l'image elle-même.
```suggestion
                                <img class="btn-icon" src="../ressources/images/plus.svg" alt="Ajouter un ingrédient">
```

2024-04-05 03:04 UTC, Vianpyro commented on ressources/scripts/monbar.js
> +const allIngredients = ["Vodka", "Rhum", "Gin", "Tequila", "Whiskey", "Triple sec", "Sirop simple", "Jus de citron", "Jus de lime", "Jus d'orange", "Jus de canneberge", "Grenadine", "Jus de pomme", "
N'oublie pas d'utiliser l'API plutot qu'une liste magique

2024-04-05 03:33 UTC, AdelnorAcmorux commented on ressources/scripts/monbar.js
> +const allIngredients = ["Vodka", "Rhum", "Gin", "Tequila", "Whiskey", "Triple sec", "Sirop simple", "Jus de citron", "Jus de lime", "Jus d'orange", "Jus de canneberge", "Grenadine", "Jus de pomme", "
Oui jai dit je fais ca demain qiand tt est p7sh

2024-04-05 03:34 UTC, AdelnorAcmorux commented on pages/testdropdown.html
> +    </script>
Nah imma dekete that

2024-04-05 03:35 UTC, AdelnorAcmorux commented
> Excellent travail, @AdelnorAcmorux! Je tiens à souligner les gros efforts que tu as investis dans cette PR. Cependant, j'ai repéré quelques petites erreurs/minor issues qui nécessitent notre attention avant de fusionner cette PR. Rien de majeur, mais corriger ces points renforcerait la qualité globale du code. J'ai remarqué beaucoup de balises `<br />`, il faudra penser à les retirer.

Derien chatgpt

2024-04-05 03:48 UTC, PabloCoroa commented on pages/testdropdown.html
> +            ul.innerHTML = ""; // Clear the list at each search
Commentaire en anglais

2024-04-05 15:43 UTC, Vianpyro commented
Yeahh, bien joué, la farouche bataille avec le Linter est enfin terminée! *(pour cette tache)*

2024-04-08 23:52 UTC, closed without merging